# Configuration parameters for running an DTDA reconstruction.  
#
# Mingsong Li, Penn State, Jan 15, 2020
# updated Feb. 2, 2020
#
# TODO
#  add function of proxy_frac, following the funciton create_proxy_lists_from_metadata_S1csv in load_proxy_data.py in LMR

core:
  # DTDA exp name
  nexp: exp_petm9_10g_all_20200218_test3
  # project directory for input data
  proj_dir: /mnt/c/Users/mul450/Dropbox/git/deepDA/mlwrk
  # work directory for outputs
  #wrkdir: /mnt/c/Users/mul450/Dropbox/git/deepDA/mlwrk/wrk
  wrkdir: /mnt/d/DeepDA/wrk
  #archive_dir: /mnt/c/Users/mul450/Dropbox/git/deepDA/mlwrk/archive
  archive_dir: /mnt/d/DeepDA/archive
  # directory for proxy data
  proxy_dir: /mnt/c/Users/mul450/Dropbox/git/deepDA/mlwrk/proxy
  # prior directory for ensemble members
  prior_dir: /mnt/d/cGENIE/ML.petm/ML.petm009
  #prior_dir: /mnt/d/cGENIE/ML.petm/ML.petm78
  #prior_dir: /mnt/d/cGENIE/ML.petm/ML.petm45

  # geologic age for Mg/Ca calibration in the baymag PSM
  geologic_age: 56.0
  # ... feature not included ...
  use_precalc_ye: True
  # ... feature not included ...
  write_posterior_Ye: True
  # reconstruction period
  recon_period: !!python/tuple [0, 2]
  # reconstruction time scale step
  recon_timescale_interval: 1
  # number of ensember
  nens: 200
  # ... feature not included ...
  #seed: null
  # covariance localization radians
  local_rad: null
  #local_rad: 20000
  # ... feature not included ...
#  inflation_fact: 1.0

  # Ensemble saving option, save full ensemble: True or False
  save_ens_full: True
  # Ensemble archiving options: ens_full, ens_variance, ens_percentiles, ens_subsample
  #save_archive: ens_variance
  #save_archive: ens_variance
  #save_archive_percentiles: !!python/tuple [5, 95]
  # Possible regridding reanalysis 2D fields
  #archive_regrid_method: null
  #archive_esmpy_interp_method: bilinear
  #archive_esmpy_regrid_to: t42

proxies:
  use_from: [NCDCdadt]
  # ... feature to be tested ...
  proxy_frac: 1.00
  proxy_frac: 0.5
  # ... feature not included ...
  proxy_timeseries_kind: asis
  # ... feature not included ...
  proxy_availability_filter: False
  # ... feature not included ...
  proxy_availability_fraction: 1.0
  # no quality control:
  proxy_qc: null
  # quality control: if innovation > 3*std of prior, ignore this observation
  #proxy_qc: 3.0
  
  NCDCdadt:
    #dbversion: 'petmproxy3slices_v0.0.10gt1.csv'
    dbversion: 'petmproxy3slices_v0.0.10g.csv'
    #dbversion: 'petmproxy3slices_v0.0.10gt2.csv'
    #dbversion: 'petmproxy3slices_v0.0.11tex.csv'
    # ... feature not included ...
    dataformat_proxy: 'DF'
    # ... feature not included ...
    regions: []
    # ... feature not included ...
    proxy_resolution: [!!python/tuple [0.,5000.]]
    
    # evaluation method: 
    #    proxy_err_psm: error derived from PSM only using real observation value
    #    proxy_err_psm_fixed: error derived from PSM only using default observation value
    #    proxy_err_psm_mp: PSM error + multiple points variance included
    proxy_err_eval: 'proxy_err_psm_fixed'
    #proxy_err_eval: 'proxy_err_psm_mp'
    # ... feature not included ...
    database_filter: []
    data_period_id: [
      'prePETMmean',
      'PETMmean',
      'postPETMmean'
    ]
    data_period_idstd: [
      'prePETMstd',
      'PETMstd',
      'postPETMstd'
    ]
    proxy_blacklist: []
    #proxy_blacklist: ['Marine sediments_d18o_pooled']
    #proxy_blacklist: ['Marine sediments_d18o_pooled','Marine sediments_tex86']
    #proxy_blacklist: ['Marine sediments_tex86']
    proxy_blacklist: [
      'Marine sediments_mgca_pooled_bcp',
      'Marine sediments_mgca_pooled_red']
    #proxy_blacklist: ['Marine sediments_tex86',
    #  'Marine sediments_mgca_pooled_bcp',
    #  'Marine sediments_mgca_pooled_red']
    #proxy_blacklist: [
    #  'Marine sediments_d18o_pooled',
    #  'Marine sediments_mgca_pooled_bcp',
    #  'Marine sediments_mgca_pooled_red']
    proxy_order: [
      'Marine sediments_uk37',
      'Marine sediments_tex86',
      'Marine sediments_d18o_pooled',
      'Marine sediments_mgca_pooled_bcp',
      'Marine sediments_mgca_pooled_red'
    ]
    proxy_psm_type:
      Marine sediments_uk37: bayesreg_uk37
      Marine sediments_tex86: bayesreg_tex86
      Marine sediments_d18o_pooled: bayesreg_d18o_pooled
      Marine sediments_mgca_pooled_red: bayesreg_mgca_pooled_red
      Marine sediments_mgca_pooled_bcp: bayesreg_mgca_pooled_bcp
    proxy_assim2:
      Marine sediments_uk37: ['uk37', 'UK37']
      Marine sediments_tex86: ['tex86', 'TEX86']
      Marine sediments_d18o_pooled: ['d18O_acarinina', 
                                     'd18o_acarinina', 
                                     'd18o_acarinina_l', 
                                     'd18o_acarinina_s',
                                     'd18o_a.praep',
                                     'd18O_a_praep',
                                     'd18o_a.soldadoensis', 
                                     'd18o_A.soldadoensis',
                                     'd18o_morozovella', 
                                     'd18O_morozovella',
                                     'd18o_m.subb', 
                                     'd18o_M.subb',
                                     'd18o_m.velascoensis']
      Marine sediments_mgca_pooled_red: ['mgca_ruber:reductive',
                                         'mgca_ruber_lato:reductive',
                                         'mgca_ruber_stricto:reductive',
                                         'mgca_sacculifer:reductive',
                                         'mgca_bulloides:reductive',
                                         'mgca_pachyderma:reductive',
                                         'mgca_morozovella:reductive',
                                         'mgca_acarinina:reductive']
      Marine sediments_mgca_pooled_bcp: ['mgca_ruber:barker',
                                         'mgca_ruber_lato:barker',
                                         'mgca_ruber_stricto:barker',
                                         'mgca_sacculifer:barker',
                                         'mgca_bulloides:barker',
                                         'mgca_pachyderma:barker',
                                         'mgca_m.subb:barker',
                                         'mgca_acarinina:barker',
                                         'mgca_m.subbotinae:barker',
                                         'mgca_m.velascoensis:barker',
                                         'mgca_morozovella:barker']

psm:
  bayesreg_tex86:
    psm_required_variables:
      ocn_sur_temp: 'full'
    temptype: 'sst'
    search_tol: 15
    nens: 5000

  bayesreg_d18o:
    psm_seatemp_variable:
      ocn_sur_temp: 'full'
    psm_d18osw_variable:
      sos_sfc_Oequ: 'full'
    psm_d18osw_from_salinity: False
    seasonal_seatemp: False

  bayesreg_d18o_pooled:
    psm_seatemp_variable:
      ocn_sur_temp: 'full'
    psm_d18osw_adjust: -0.96

  bayesreg_mgca:
    psm_seatemp_variable:
      ocn_sur_temp: 'full'
    seasonal_seatemp: False
    seawater_age: 56.0

prior:
  prior_source: cgenie_36x36

  cgenie_36x36:
  
    # longitude offset degree
    dum_lon_offset: -180.0
    # State variable to be analyzed
    state_variable:
      # DA 2d (lon-lat, surface/benthic) or 3d (lon-lat-depth)
      2d:
        ncname:
          biogem: 'fields_biogem_2d'
        #fields_biogem_2d: ['ocn_sur_temp',
        #  'atm_pCO2']
        
        # Warning: all proxy data associated with 
        #    ocn_sur_temp, which must be the first field       
        
        #fields_biogem_2d: ['ocn_sur_temp']
        #fields_biogem_2d: [
        #    'ocn_sur_temp',
        #    'sed_CaCO3',
        #    'atm_pCO2'
        #    ]
        fields_biogem_2d: [
            'ocn_sur_temp',
            'sed_CaCO3',
            'atm_pCO2',
            'ocn_sur_sal',
            'misc_pH',
            'carb_sur_ohm_cal'
            ]
        #fields_biogem_2d: ['ocn_sur_temp',
        #  'atm_pCO2',
        #  'atm_temp']
        #fields_biogem_2d: ['ocn_sur_temp',
        #  'atm_temp',
        #  'atm_pCO2',
        #  'ocn_ben_DIC_13C',
        #  'ocn_sur_DIC_13C']
      # DA 2d (lon-lat, surface/benthic) or 3d (lon-lat-depth)
      3d:
        ncname: 
          biogem: 'fields_biogem_3d'
        fields_biogem_3d: []
        #fields_biogem_3d: ['carb_ohm_cal']
        #fields_biogem_3d: ['ocn_temp',
        #   'misc_pH']
        #fields_biogem_3d: ['ocn_temp',
        #  'misc_pH',
        #  'ocn_O2',
        #  'ocn_DIC_13C',
        #  'phys_u',
        #  'phys_v'] 
      
    